refactor(views/library): 修改取词逻辑
qier222/YesPlayMusic pull request #1135
Opened 2021-12-27 12:20 UTC by pan93412

Closed #1133 (把 commit history 清乾淨一點)

2021-12-27 12:21 UTC, pan93412 commented
@isNijikawa 你這裡 E2E 測試沒問題，對嗎？

r? @qier222

2021-12-27 16:47 UTC, qier222 commented on src/views/library.vue
> +          var promise = data.lrc.lyric.split('\n').filter(l => {
不能用var，得用const或let

2021-12-27 21:09 UTC, isNijikawa commented
> @isNijikawa 你這裡 E2E 測試沒問題，對嗎？
> 
> r? @qier222

我本地的测试都没有问题, 测试用例贴在了 issue #1019.

2021-12-27 21:13 UTC, isNijikawa requested changes
我最开始用的是 let,可以改回去.

2021-12-27 23:10 UTC, pan93412 commented
r? @isNijikawa @qier222

2021-12-28 09:55 UTC, memorydream approved these changes

2021-12-28 09:58 UTC, memorydream commented
刚刚没注意，好像有点问题？过滤部分好像没有异步？

2021-12-28 09:58 UTC, merged

2021-12-28 09:58 UTC, memorydream commented
这样子可以吗？我先试试吧

2021-12-28 10:10 UTC, memorydream commented
OK，这个修复没有问题

2021-12-28 10:19 UTC, memorydream commented
@pan93412 不好意思，我需要撤回我的话，这个修改并没有完全修复问题，有内存泄漏

2021-12-28 10:22 UTC, pan93412 commented
> @pan93412 不好意思，我需要撤回我的话，这个修改并没有完全修复问题，有内存泄漏
> 
> 正常占用300+MB，当我在音乐库和我喜欢的音乐来回切换时，可以明显观察到内存占用快速上升

照理來講無關。你能幫我確定一下是不是其他 commit 導致的嗎？

2021-12-28 10:32 UTC, memorydream commented
> > @pan93412 不好意思，我需要撤回我的话，这个修改并没有完全修复问题，有内存泄漏
> > 正常占用300+MB，当我在音乐库和我喜欢的音乐来回切换时，可以明显观察到内存占用快速上升
> 
> 照理來講無關。你能幫我確定一下是不是其他 commit 導致的嗎？

一份 11月20号 构建的版本，一直刷到卡死，没有出现我在这里报告的问题

2021-12-28 10:56 UTC, pan93412 commented
自行測試後，Electron App 本身 DevTools 抓到的 Heap Profile 沒有明顯增長，Activity Monitor 考慮到我有 snapshot，其增長也在合理範圍。下附錄影檔。

## Before

### 測試版本
<img width="762" alt="build-9fecff1d-commit" src="https://user-images.githubusercontent.com/28441561/147558763-ea7cf635-6d48-4312-9748-2809cbd91f9c.png">

### 錄影

https://user-images.githubusercontent.com/28441561/147559225-b1319511-11f3-4d4c-b5f0-9a1d467f22a8.mp4

## After

使用的版本是最新提交的組建。

### 錄影

https://user-images.githubusercontent.com/28441561/147559262-f3cf407e-af69-4747-a5c5-f4101a763007.mp4

2021-12-28 12:19 UTC, memorydream commented
我不确定在这里发生了什么，但是我现在发现在我的歌单里还是发生了卡死现象，我先确定这个问题