feat: 支持二维码登录
qier222/YesPlayMusic pull request #1443
Opened 2022-03-26 08:19 UTC by BakerBunker

1. 修复因为replace函数导致的bug

     - 原来的replace('HTTPOnly','')函数只能替换一个，所以替换为replaceAll。
     - 在扫码返回的cookie中HTTPOnly是以'; HTTPOnly;'出现的，为了能够同时替换含有空格和不含空格的格式，使用了正则表达式。

2. 支持二维码登录

2022-03-26 08:22 UTC, qier222 commented on packages/renderer/src/utils/cookie.ts
> +  const cookies = string.replaceAll(/;.*?HTTPOnly.*?;/g, ';;').split(';;')
replaceAll的兼容性暂时不太够（参考 https://caniuse.com/?search=replaceAll ），建议换成replace+正则

2022-03-26 08:26 UTC, qier222 commented on packages/renderer/src/pages/Login.tsx
> +  useEffect(()=>{
尝试看看用React Query？另外 .then 可以用 async await 语法来代替，会更简洁一些

2022-03-26 08:27 UTC, qier222 commented on packages/renderer/src/pages/Login.tsx
> +  useEffect(()=>{
提示都可以写中文，暂时不打算做i18n适配

2022-03-26 08:42 UTC, pan93412 commented on packages/renderer/src/utils/cookie.ts
> +  const cookies = string.replaceAll(/;.*?HTTPOnly.*?;/g, ';;').split(';;')
很足夠了吧⋯⋯2020 年以後瀏覽器的基本上都支援。此外如果你真的想要支援更舊的裝置，我們也可以加上 polyfill。

<img width="493" alt="截圖 2022-03-26 下午4 41 23" src="https://user-images.githubusercontent.com/28441561/160231834-bd20c6a0-06cb-4884-98aa-5f8eba0bd809.png">

2022-03-26 08:55 UTC, BakerBunker commented on packages/renderer/src/utils/cookie.ts
> +  const cookies = string.replaceAll(/;.*?HTTPOnly.*?;/g, ';;').split(';;')
可以用replace,global regex和replace应该也可以直接全局替换

2022-03-26 08:56 UTC, qier222 commented on packages/renderer/src/utils/cookie.ts
> +  const cookies = string.replaceAll(/;.*?HTTPOnly.*?;/g, ';;').split(';;')
在这个情况下replaceAll和replace输出的结果是一样的，正则里并没有写明只匹配一次

```
string = "xxxxx;HTTPOnly;xxxxx;xxxx;HTTPOnly;xxxxxxx"

string.replaceAll(/;.*?HTTPOnly.*?;/g, ';;')
';;xxxxx;;'

string.replace(/;.*?HTTPOnly.*?;/g, ';;')
';;xxxxx;;'
```

2022-03-26 10:11 UTC, qier222 commented on packages/renderer/src/pages/Login.tsx
> +      setQrCodeUrl(`https://music.163.com/login?codekey=${key.data.unikey}`)
建议用useState存储key，然后用useMemo来计算 qrCodeUrl

2022-03-26 10:14 UTC, qier222 commented on packages/renderer/src/pages/Login.tsx
> +    status: key_status,
这里要用驼峰变量名

2022-03-26 10:15 UTC, qier222 commented on packages/renderer/src/pages/Login.tsx
> +      setQrCodeUrl(`https://music.163.com/login?codekey=${key.data.unikey}`)
不建议对api返回的数据进行提取，因为目前在项目里其他地方都是不对数据修改的，统一一下比较好

2022-03-26 10:16 UTC, qier222 commented on packages/renderer/src/pages/Login.tsx
> +      setQrCodeUrl(`https://music.163.com/login?codekey=${key.data.unikey}`)
用 onError, onSettled,  onSuccess这些React Query提供的选项来处理API错误比较好

2022-03-26 11:09 UTC, qier222 commented on packages/renderer/src/pages/Login.tsx
> +  useMemo(async () => {
```
const qrCodeUrl =  useMemo(() => {
    return `https://music.163.com/login?codekey=${qrCodeKey}`
  }, [qrCodeKey])
```

2022-03-26 11:12 UTC, qier222 commented on packages/renderer/src/pages/Login.tsx
>    useMemo(async () => {
这里也是应该用 `const qrCodeImage = useMemo(()=>{},[])` 这种写法

2022-03-26 11:57 UTC, pan93412 requested changes

2022-03-26 11:57 UTC, pan93412 commented on packages/renderer/src/pages/Login.tsx
>    }, [qrCodeKey])
這裡可以簡化成：

```js
const qrCodeUrl = useMemo(
  () => `https://music.163.com/login?codekey=${qrCodeKey}`,
  [qrCodeKey]
);
```

2022-03-26 11:57 UTC, pan93412 commented on packages/renderer/src/pages/Login.tsx
> +  useEffect(() => {
可以直接 `async () => { /* 你的 updateImage */ }`。

2022-03-26 11:59 UTC, pan93412 commented on packages/renderer/src/pages/Login.tsx
> +  useEffect(() => {
🤔 好像不是推薦的寫法⋯⋯

2022-03-26 12:54 UTC, pan93412 requested changes
此外應該就沒問題了。

2022-03-26 12:54 UTC, pan93412 commented on packages/renderer/src/pages/Login.tsx
> +    },
這裡同樣可以省掉 return，改成 `() => loginWithEmail()` 的形式。

2022-03-26 16:35 UTC, qier222 commented on packages/renderer/src/pages/Login.tsx
> +        setQrCodeKey(data.data.unikey)
不需要setQrCodeKey，useQuery会返回api的数据，直接从数据里读取就好了。要尽量少用setXXX，因为每一次setXXX都会让组件重新渲染一遍。
另外不需要手动 refetchKey()，React Query应该会自动重试

2022-03-26 18:19 UTC, BakerBunker commented on packages/renderer/src/pages/Login.tsx
> +        setQrCodeKey(data.data.unikey)
第二条应该是需要的，react query重试的情况应该只会在和NeteaseCloudMusicApi通信出现问题的时候才会出现，否则status code只会是200，只是返回值data里面的code会有差别，这个是api的代码
```javascript
// module/login_qr_key.js
  return {
    status: 200,
    body: {
      data: result.body,
      code: 200,
    },
    cookie: result.cookie,
  }
```
可以改成这样
```typescript
  const {
    data: key = { code: 200, data: { code: 200, unikey: 'Not Ready' } },
    status: keyStatus,
    refetch: refetchKey,
  } = useQuery('qrCodeKey', fetchLoginQrCodeKey, {
    onSuccess: data => {
      if (data.data.code !== 200) {
        toast(`Failed to fetch QR code key: ${data.data.code}`)
        refetchKey()
        return
      }
    },
  })
```
不用initialData是因为[这个](https://github.com/tannerlinsley/react-query/discussions/1301)
但改成这样也不合适，会导致api和外部通信出问题的时候不断refetch，我不知道这种情况要在哪里解决，是不是可以在queryFn里面抛出异常，再用react query的错误处理去重试，像这样
```typescript
  const {
    data: key = { code: 200, data: { code: 200, unikey: 'Not Ready' } },
    status: keyStatus,
    refetch: refetchKey,
  } = useQuery(
    'qrCodeKey',
    async () => {
      const result = await fetchLoginQrCodeKey()
      if (result.data.code !== 200) {
        throw Error(`Failed to fetch QR code key: ${result.data.code}`)
      }
      return result
    },
    {
      retry: true,
      retryDelay: 500,
    }
  )
```

2022-03-27 06:38 UTC, qier222 commented on packages/renderer/src/pages/Login.tsx
> +        setQrCodeKey(data.data.unikey)
throw Error的方案看起来不错

2022-03-27 07:04 UTC, pan93412 commented
@qier222 之後記得用 squash 的方式進去 `react`

2022-03-27 08:04 UTC, merged