fix: bugs
qier222/YesPlayMusic pull request #1503
Opened 2022-04-09 08:33 UTC by memorydream

2022-04-09 13:58 UTC, pan93412 requested changes

2022-04-09 13:58 UTC, pan93412 commented on src/renderer/components/Lyric/Player.tsx
> +  const playerMode = useMemo(() => playerSnapshot.mode, [playerSnapshot.mode])
沒有必要這麼做

2022-04-09 13:58 UTC, pan93412 commented on src/renderer/utils/player.ts
> +    if (this.fmTrackList?.length <= 5) {
`5` 這個數字代表什麼意義？建議 comment 一下。

2022-04-09 14:06 UTC, memorydream commented on src/renderer/utils/player.ts
> +    if (this.fmTrackList?.length <= 5) {
我也不知道，qier222在下面的加载代码里写的长度限制也是5，为了保持一致，所以这里也是5

2022-04-09 15:25 UTC, qier222 commented on src/renderer/components/FMCard.tsx
> +            <div className='line-clamp-3 text-xl font-semibold'>
感觉限制到两行比较好

2022-04-09 15:26 UTC, qier222 commented on src/renderer/components/Lyric/Player.tsx
> +  const hasListSource = playerSnapshot.mode !== PlayerMode.FM && trackListSource?.type
这个判断如果没复用的话感觉可以放到函数内

2022-04-09 15:28 UTC, memorydream commented on src/renderer/components/Lyric/Player.tsx
> +  const hasListSource = playerSnapshot.mode !== PlayerMode.FM && trackListSource?.type
复用了，两个地方用了这个

2022-04-09 15:29 UTC, memorydream commented on src/renderer/components/FMCard.tsx
> +            <div className='line-clamp-3 text-xl font-semibold'>
这里是我测过，歌名三行 + 歌手两行，刚好全部占满，如果你想空出一行，那这里可以是两行

2022-04-09 15:30 UTC, qier222 commented on src/renderer/utils/player.ts
> +    if (this.fmTrackList?.length <= 5) {
这里感觉可以改一下判断，如果fmTrackList是空的话，就await请求。
然后 <=5 这个可以做成异步的，这样可以尽量减少阻塞fm初始化

2022-04-09 15:31 UTC, qier222 commented on src/renderer/utils/player.ts
> +    if (this.fmTrackList?.length <= 5) {
<=5 这个逻辑可以看作是 prefetch

2022-04-09 15:33 UTC, memorydream commented on src/renderer/utils/player.ts
> +    if (this.fmTrackList?.length <= 5) {
这里只是判断了长度吧？里面的匹配逻辑还是await，理论上来讲这里应该是不会阻塞？

2022-04-09 15:38 UTC, memorydream commented on src/renderer/utils/player.ts
> +    if (this.fmTrackList?.length <= 5) {
或者这里逻辑改成优先初始化fmTrack？然后长度不够再fetchPersonalFM

2022-04-10 15:29 UTC, qier222 commented on src/renderer/components/FMCard.tsx
> +            <div className='line-clamp-3 text-xl font-semibold'>
歌名和歌手都是两行吧

2022-04-10 15:30 UTC, qier222 commented on src/renderer/utils/player.ts
>      const prefetchNextTrack = async () => {
这个应该是内部方法吧

2022-04-10 15:37 UTC, merged