Update playing status on sidebar playlists
qier222/YesPlayMusic pull request #1517
Opened 2022-04-11 04:25 UTC by L-Ryland

RT

2022-04-11 04:59 UTC, memorydream requested changes

2022-04-11 04:59 UTC, memorydream commented on src/renderer/components/Sidebar.tsx
> +  const isPlaying = true
这个变量好像没有使用？

2022-04-11 04:59 UTC, memorydream commented on src/renderer/components/Sidebar.tsx
> +          {currentPlaylistID == playlist.id
考虑一下当前是否是FM模式的情况？

2022-04-11 05:05 UTC, qier222 commented on src/renderer/utils/player.ts
> +  private _playlist = {playlistID: 0}
这个变量和 trackListSrouce 重复了

2022-04-12 07:49 UTC, qier222 commented on src/renderer/components/Sidebar.tsx
> +] as const
@pan93412 麻烦看看这样写ts是否有问题？

2022-04-12 07:49 UTC, qier222 commented on src/renderer/components/Sidebar.tsx
> +          style={{ justifyContent: 'space-between' }}
这里可以用tailwind的class，不需要用style

2022-04-12 07:52 UTC, qier222 commented on src/renderer/components/Sidebar.tsx
> +  const currentPlaylistID = useMemo(() => playerSnapshot.trackListSource?.id, [playerSnapshot.trackListSource])
这里的缩进格式没有搞好，建议commit之前执行一下 `pnpm run prettier`

2022-04-12 07:57 UTC, qier222 commented on src/renderer/components/Sidebar.tsx
> +          style={{ justifyContent: 'space-between' }}
并且这个div也没有 `display: flex` ?

2022-04-12 08:33 UTC, memorydream approved these changes

2022-04-12 08:36 UTC, memorydream commented on src/renderer/components/Sidebar.tsx
> +    player.playOrPause()
这个好像也没有使用？

2022-04-12 08:37 UTC, qier222 commented on src/renderer/components/Sidebar.tsx
> +          {mode == Mode.PLAYLIST && currentPlaylistID == playlist.id
这里需要用 `===` 而不是 `==`

2022-04-12 12:21 UTC, qier222 commented on src/renderer/components/Sidebar.tsx
> +] as const
建议恢复到之前的写法，然后 `icon: SvgName`
`SvgName` 是从 `SvgIcon.tsx` 导入的

2022-04-12 12:23 UTC, qier222 commented on src/renderer/components/SvgIcon.tsx
> +type svgName = 'back' | 'dislike' | 'dj' | 'email' | 'explicit' | 'eye-off' | 'eye' | 'fm' | 'forward' | 'heart-outline' | 'heart' | 'home' | 'lock' | 'lyrics' | 'more' | 'music-library' | 'music-not
建议将 `svgName` 改为 `SvgName`， type 一般是PascalCase的

2022-04-12 12:53 UTC, qier222 commented on src/renderer/components/Sidebar.tsx
> +          <SvgIcon className='mr-3 h-6 w-6' name={tab['icon']} />
应该写成 tab.icon

2022-04-12 13:05 UTC, memorydream commented on src/renderer/components/Sidebar.tsx
> +              'btn-hover-animation line-clamp-1 my-px mx-3 flex flex cursor-default items-center justify-between rounded-lg px-3 py-[0.38rem] text-sm text-black opacity-70 transition-colors duration-
这里出现了两个`flex`

2022-04-12 13:45 UTC, qier222 commented on src/renderer/components/Sidebar.tsx
> +          {mode === Mode.PLAYLIST && currentPlaylistID === playlist.id && (
要加 `&& playerSnapshot.trackListSource.type === TrackListSourceType.PLAYLIST`

2022-04-12 14:18 UTC, merged

2022-04-12 14:19 UTC, qier222 commented
感谢贡献代码