feat:  使用qrcode-svg替换qrcode
qier222/YesPlayMusic pull request #1565
Opened 2022-04-26 05:27 UTC by memorydream

2022-04-26 06:11 UTC, pan93412 requested changes

2022-04-26 06:11 UTC, pan93412 commented on src/views/loginAccount.vue
> +            v-html="qrCodeSvg"
盡量避免使用 v-html

2022-04-26 06:20 UTC, memorydream commented on src/views/loginAccount.vue
> +            v-html="qrCodeSvg"
这个包没办法，输出就是一个完整的svg标签

2022-04-26 08:29 UTC, memorydream commented on src/views/loginAccount.vue
> +            v-html="qrCodeSvg"
用了一个比较脏的做法避免 v-html，请review

2022-04-27 01:13 UTC, pan93412 commented
🌚 還是 v-html 好了⋯⋯

2022-04-27 05:01 UTC, memorydream commented
> 🌚 還是 v-html 好了⋯⋯

把这个包fork一份改一下？我想在v2里也用这个，v2里有主题色的修改，每次重新生成新的svg感觉不太合适

2022-04-27 06:21 UTC, memorydream commented
现在我测试是没有问题了，但是这个库有一个潜在的问题，它的样式是写在svg的`style`内

2022-04-27 06:41 UTC, closed without merging