feat: UNM 设置页面 l10n
qier222/YesPlayMusic pull request #1578
Opened 2022-04-28 14:54 UTC by memorydream

2022-04-28 17:16 UTC, pan93412 requested changes

2022-04-28 17:16 UTC, pan93412 commented on src/locale/lang/tr.js
> +        desc: 'Need to clear the cache to take effect after enable',
To take effect, it may be required to clear the cache after enabling this function.

2022-04-28 17:16 UTC, pan93412 commented on src/locale/lang/tr.js
> +        desc1: 'Setting description see here',
Click here for the configuration instruction.

2022-04-28 17:16 UTC, pan93412 commented on src/locale/lang/tr.js
> +        desc2: 'not apply setting if value is empty',
Leave empty to pick up the default value

2022-04-28 17:16 UTC, pan93412 commented on src/locale/lang/tr.js
> +      ytdl: 'Youtube-dl execute file',
The youtube-dl Executable File for YtDl

2022-04-28 17:16 UTC, pan93412 commented on src/locale/lang/tr.js
> +        title: 'For UNM Proxy',
Proxy Server for UNM

2022-04-28 17:16 UTC, pan93412 commented on src/locale/lang/tr.js
> +        desc1: '请求如 YouTube 音源服务时要使用的代理服务器',
The proxy server to use for requesting services such as YouTube.

2022-04-28 17:16 UTC, pan93412 commented on src/locale/lang/tr.js
> +        desc2: '留空则不进行相关设置',
Leave empty to pick up the default value

2022-04-28 17:17 UTC, pan93412 commented
`en.js` 之建議與 `tr.js` 相同。

2022-04-29 04:03 UTC, memorydream commented on src/views/settings.vue
> +        <h3>UnblockNeteaseMusic</h3>
我不建议在此处保留`设置`一词，因为这个已经在设置里，仅使用`UnblockNeteaseMusic`已经足够传达意图

2022-04-29 04:05 UTC, memorydream commented on src/views/settings.vue
>                音源的具体代号
此处没有l10n，因为此处的描述穿插了多个html标签，不是很好处理

2022-04-29 05:16 UTC, pan93412 commented on src/locale/lang/zh-TW.js
> +        desc: '啟用后需要清除歌曲快取才能生效',
啟用「後」

2022-04-30 00:46 UTC, pan93412 approved these changes

2022-04-30 06:49 UTC, merged