fix(components/TrackList): 修复在播放私人 FM 音乐时无法通过右键菜单播放、添加歌单歌曲
qier222/YesPlayMusic pull request #1614
Opened 2022-05-04 15:32 UTC by waterblock79

Bug：当播放来自私人 FM 的音乐时，在歌单页右键歌单歌曲：进行「播放」操作时没有播放这一首歌单歌曲，而是私人 FM 的歌曲出现了切换下一首歌的反应；进行「添加到队列」操作时无反应。  
![](https://user-images.githubusercontent.com/33573572/166708270-dc829c58-aea3-4399-ac78-16423e162ff6.gif)  
修复效果：  
![](https://user-images.githubusercontent.com/33573572/166715189-5a515584-3a91-4b53-9359-30229412949a.gif)

2022-05-05 01:30 UTC, pan93412 requested changes

2022-05-05 01:30 UTC, pan93412 commented on src/components/TrackList.vue
> +      if (this.player._isPersonalFM) this.player._isPersonalFM = false;
為何要這樣改？感覺就會跟私人 FM 播放/暫停的邏輯衝突到。建議撰寫完整的 comment 說明清楚其功用、影響。

2022-05-05 01:30 UTC, pan93412 commented on src/components/TrackList.vue
> +      if (this.player._isPersonalFM) this.player._isPersonalFM = false;
同 L229

2022-05-05 03:20 UTC, waterblock79 commented on src/components/TrackList.vue
> +      if (this.player._isPersonalFM) this.player._isPersonalFM = false;
这里改的是歌单的右键菜单的操作，应该不会和私人 FM 的操作冲突（

![2022-05-05 11-10-06](https://user-images.githubusercontent.com/33573572/166859184-d6a63ab0-27b1-4add-93fe-f50176659521.gif)

2022-05-05 03:27 UTC, waterblock79 commented on src/components/TrackList.vue
> +      if (this.player._isPersonalFM) this.player._isPersonalFM = false;
改的原因见Bug描述，在播放私人 FM 音乐的时候，点击歌单内右键菜单的播放摁键出现了错误的反应、点击添加到队列摁键无反应。这样改一下使点击歌单这两个键的时候取消私人 FM 模式，让播放器能正确的播放用户所要播放的歌曲。

2022-05-06 00:56 UTC, qier222 commented on src/components/TrackList.vue
> +      if (this.player._isPersonalFM) this.player._isPersonalFM = false;
我觉得更适合得解决方法是，在FM模式下也优先播放“插播的歌曲“

2022-05-07 07:46 UTC, memorydream commented
https://github.com/qier222/YesPlayMusic/blob/9e787bab0332e67c665d73ef0712f42ee8b374c7/src/utils/Player.js#L838-L847

我认为修改这里更好，只要把私人FM相关的代码直接删了就行，记得设置`_isPersonalFM`

2022-05-18 14:43 UTC, waterblock79 commented
要备考了，再开发的时候要么不给api发请求、要么环境装不上，也没啥精力折腾了，我先关pr了吧，一直挂着不太好，抱歉麻烦到你们了（

2022-05-18 14:43 UTC, closed without merging