feat: add shuffle play
qier222/YesPlayMusic pull request #1616
Opened 2022-05-04 20:04 UTC by L-Ryland

2022-05-05 01:28 UTC, pan93412 requested changes

2022-05-05 01:28 UTC, pan93412 commented on src/renderer/components/Cover.tsx
> +  )
[unneeded-memo] 這個 useMemo 老實說很沒必要⋯⋯直接寫 `const trackListSource = playerSnapshot.trackListSource;` 就好

2022-05-05 01:28 UTC, pan93412 commented on src/renderer/components/Cover.tsx
> +  )
同上。

2022-05-05 01:28 UTC, pan93412 commented on src/renderer/components/Player.tsx
> +  const shuffleMode = useMemo(() => playerSnapshot.shuffle, [playerSnapshot.shuffle])
unneeded-memo

2022-05-05 01:28 UTC, pan93412 commented on src/renderer/utils/player.ts
> +    const howler: Howl = new Howl({
unneeded declaration

2022-05-05 01:28 UTC, pan93412 commented on src/renderer/utils/player.ts
> +    (window as any).howler = howler
[explicit-declaration] 建議改在 `globals.d.ts` 宣告：

```ts
declare global {
  interface Window {
    // ...
    howler: Howler
  }
}
```

2022-05-05 01:28 UTC, pan93412 commented on src/renderer/utils/player.ts
> +  playShuffle(list: TrackID[], trackID?: TrackID) {
[naming-or-doc] 命名建議改得更明確（或增加文件）

2022-05-05 01:28 UTC, pan93412 commented on src/renderer/utils/player.ts
> +  (window as any).howler = _howler
explicit-declaration

2022-05-05 01:28 UTC, pan93412 commented on src/renderer/components/CoverRow.tsx
> +  const getCoverInfo = (id: number): TrackListSource | undefined => {
naming-or-doc

2022-05-05 03:58 UTC, memorydream commented
有上一个还没有合并的pr里的内容，请清理一下，只留下这个pr里必须的内容

2022-05-05 09:42 UTC, L-Ryland commented
pr內容已清理

2022-05-06 04:02 UTC, pan93412 commented
@L-Ryland 幫我把這次的 review 移植到 #1526, thanks!

2023-05-09 04:40 UTC, closed without merging