Update README.md
qier222/YesPlayMusic pull request #1731
Opened 2022-07-13 09:31 UTC by jbwfu

添加 Replit 部署方式

2022-07-21 02:03 UTC, pan93412 requested changes

2022-07-24 04:08 UTC, pan93412 approved these changes
code 如果能清理跟格式化一下會更好，但基本上 LGTM。

2022-07-25 05:26 UTC, qier222 commented
`npm run serve` 是开发模式，建议build出来后再用类似 serve(https://www.npmjs.com/package/serve) 这样的包来提供http服务

2022-08-21 13:37 UTC, jbwfu commented
而且似乎只有单独部署 api 时 api 才可用 否则会 405

2022-08-31 04:08 UTC, merged