feat: Add status text to like button when hover event triggers
qier222/YesPlayMusic pull request #1789
Opened 2022-08-30 07:03 UTC by kayw-geek

Add unlike text to like button when hover event triggers

2022-08-30 07:10 UTC, pan93412 requested changes

2022-08-30 07:10 UTC, pan93412 commented on src/locale/lang/zh-TW.js
> +    unlike: '取消中意',
「取消喜歡」is better — to match the translation of “like.”

2022-08-30 07:47 UTC, kayw-geek commented on src/locale/lang/zh-TW.js
> +    unlike: '取消中意',
Okay, thank your review, I have changed it.

2022-08-30 07:59 UTC, pan93412 approved these changes

2022-08-31 04:03 UTC, pan93412 approved these changes

2022-09-09 04:45 UTC, merged