feat: osdlyrics support on linux platform
qier222/YesPlayMusic pull request #1818
Opened 2022-10-05 08:27 UTC by Revincx

特性：在 Linux 下支持了桌面歌词软件 [OSDLyrics](https://github.com/osdlyrics/osdlyrics)，可以根据需要在设置里开启。
特性：状态栏小图标新增了一个暗色风格的，可以根据系统设置的主题风格切换。

附一张在 ArchLinux 下的截图：
![image_2022-10-05_16-05-36](https://user-images.githubusercontent.com/25524750/194015734-6af72988-bac0-4813-b2f6-c76b98b6270e.png)

2022-10-22 03:54 UTC, pan93412 requested changes
辛苦了，這裡是一些 suggestion 供你參考～

2022-10-22 03:54 UTC, pan93412 commented on src/locale/lang/en.js
> +      desc: 'Only takes effect under Linux. After enable, I will download the lyrics file to the local, and try to launch OSDLyrics at startup',
```plain
Only takes effect under Linux. After enabled, it downloads the lyrics file to the local, and tries to launch OSDLyrics at startup.
```

2022-10-22 03:54 UTC, pan93412 commented on src/locale/lang/zh-CN.js
> +      title: '桌面歌词支持',
`启用「桌面歌词」支持` can be better?

2022-10-22 03:54 UTC, pan93412 commented on src/locale/lang/zh-TW.js
> +      title: '桌面歌詞支持',
`啟用「桌面歌詞」支援`

2022-10-22 03:54 UTC, pan93412 commented on src/locale/lang/zh-TW.js
> +      desc: '僅 Linux 下生效，開啟後將會下載歌詞文件到本地，並會嘗試在啟動時拉起 OSDLyrics',
`只在 Linux 環境下生效。啟用後會將歌詞檔案下載至本機位置，並在開啟播放器時嘗試連帶啟動 OSDLyrics。`

2022-10-22 03:54 UTC, pan93412 commented on src/locale/lang/zh-CN.js
> +      desc: '仅 Linux 下生效，开启后将会下载歌词文件到本地，并会尝试在启动时拉起 OSDLyrics。',
`仅 Linux 下生效。启用后会将歌词文件下载到本地，并在开启播放器时尝试拉起 OSDLyrics。`

2022-10-22 03:54 UTC, pan93412 commented on src/electron/ipcMain.js
> +    let lyricsDirPath = resolve(process.env.HOME, '.lyrics');
放在 `~/.cache` 之類的路徑會不會更好？畢竟都會自動下載。

2022-10-22 03:54 UTC, pan93412 commented on src/electron/ipcMain.js
> +  ipcMain.on('saveLyric', (event, { name, lyric }) => {
IPC 是可以非同步的，而 `Sync` 類函數很可能會堵住整個 event loop。另外 existsSync 這樣的判斷有可能會造成 race condition——我重寫了一個比較可靠（另外判斷了其他可能會發生的情況）的寫法，可以供你參考：

```js
import { writeFile, mkdir, rm } from "fs/promises";
import { resolve } from "path";
import { homedir } from "os";

const TMPDIR = resolve(homedir(), ".cache");

async function writeLyric(name, content) {
  const destination = resolve(TMPDIR, name);

  try {
    // 考慮到寫入歌詞檔案的開銷不大，我覺得直接寫入就好。
    // 快取有可能導致 NCM 那邊的新歌詞沒有辦法同步進 OSDLyric。
    await writeFile(destination, content);
  } catch (e) {
    switch (e?.code) {
      // ENOENT (no such file or directory)，
      case "ENOENT":
        await mkdir(TMPDIR, { recursive: true });

        // Try again. Should be succeed.
        return writeLyric(name, content);
      // ENOTDIR (not a directory), 指 TMPDIR 有問題。
      case "ENOTDIR":
        // 砍掉 TMPDIR「檔案」。
        await rm(TMPDIR);

        // 預期接下來的流程是 ENOENT 建立資料夾的流程。
        return writeLyric(name, content);
    }

    throw e;
  }
}
```

2022-10-22 03:54 UTC, pan93412 commented on src/utils/Player.js
> +      name: lyricName,
這裡傳入的 lyric name 有個潛在問題：

- 假如歌詞裡面包含 `/`，這樣寫入的歌詞路徑會不會不合預期？
  <img width="501" alt="image" src="https://user-images.githubusercontent.com/28441561/197317866-d9697672-6fc7-4e0e-97f3-2cc0c240a274.png">
- 假如歌詞裡面有 `../` 和 `./` 之類的字眼，這樣子會不會變相可以「用這種歌名和偽造的歌詞資料，將惡意程式碼注入使用者的環境？」
  <img width="702" alt="image" src="https://user-images.githubusercontent.com/28441561/197317979-4ce334fa-2199-40b0-bdee-028542ddf9e7.png">


我的建議是用 `SHA-1` 或 `UUID` 等 1-1 hash 語法，先將檔名變成人畜無害的隨機字串，再寫入可能會更安全。

2022-10-22 05:42 UTC, Revincx commented on src/utils/Player.js
> +      name: lyricName,
感谢建议！

关于翻译和 ipcMain 中非同步写入的问题已经在更改中。但是关于歌词文件位置和文件名的问题有点难处理。这是因为 OSDLyrics 寻找并读取歌词文件的方式比较简单暴力，当 OSDLyrics 从 mpris 监听到曲目名称变化时，会自动读取 $HOME/.lyrics 中相应名字的 .lrc 文件。虽然这个目录可以在 OSDLyrics 的设置中自定义，但是这无疑增添了麻烦。
![image](https://user-images.githubusercontent.com/25524750/197320134-4d0ea3b2-aa13-4fc8-8678-383628d4f106.png)

至于曲目名称中可能含有 `/` 的问题，可以通过把 `/` 替换为 `⁄` 解决，但是这么做之后似乎 OSDLyrics 就寻找不到对应文件了，大概是 OSDLyrics 的问题。

2022-10-22 05:56 UTC, Revincx commented on src/locale/lang/en.js
> +      title: 'desktop lyrics support',
另外关于此处翻译，我认为“启用桌面歌词支持”可能会带来误解。因为这个功能的前提是用户的系统中已经安装了 osdlyrics。另外我在这个设置项的标题中为 “OSDLyrics” 添加了超链接，目的就是为了引导可能为安装 osdlyrics 的用户去下载安装。所以我认为这个部分保留比较合适。

2022-10-22 09:21 UTC, pan93412 commented on src/utils/Player.js
> +      name: lyricName,
那我覺得大概只能維持現狀，不過把 `/` 替換成空格能夠匹配嗎？

2022-10-22 10:06 UTC, Revincx commented on src/utils/Player.js
> +      name: lyricName,
> 那我覺得大概只能維持現狀，不過把 `/` 替換成空格能夠匹配嗎？

把名称中的 `/` 替换成空格？为什么这样做呢？应该不能匹配吧，osdlyrics 目前只支持精确匹配，而且我觉得这是 osdlyrics 的一个问题，它应该在获取曲目名称时自动替换 `/` 为 `⁄`然后再去寻找对应的 lrc 文件。或许应该向那边提出 issue ?

2023-04-09 05:36 UTC, alex3236 commented on src/utils/Player.js
> +      name: lyricName,
![image](https://user-images.githubusercontent.com/45303195/230756294-4fb4ddd0-7b57-4b1d-a658-04a9a0de4a95.png)
OSDLyrics似乎能正常读取将`/`替换为`_`的歌词。

2023-08-25 23:58 UTC, pan93412 approved these changes

2023-08-26 00:11 UTC, Revincx commented
昨天改用 dbus 实现歌词文件下载了，先等我合并到这个分支来

2023-08-26 01:05 UTC, Revincx commented
@pan93412 应该改好了，麻烦看下

2023-08-26 02:09 UTC, pan93412 requested changes

2023-08-26 02:09 UTC, pan93412 commented on src/locale/lang/en.js
> +        'Please ensure that you have installed OSDLyrics before turn on this.',
`turning`

2023-08-26 02:10 UTC, Revincx commented on src/locale/lang/en.js
> +        'Please ensure that you have installed OSDLyrics before turn on this.',
😭

2023-08-26 02:14 UTC, pan93412 approved these changes

2023-08-26 02:14 UTC, pan93412 commented
你準備好之後就可以合併了～

2023-08-26 02:15 UTC, Revincx commented
> 你準備好之後就可以合併了～

应该没啥问题了👀

就是一下拉了这么一大堆 commit 是不是有点乱

2023-08-26 02:16 UTC, pan93412 commented
你可以 `git rebase -i origin/master` 整理一下

2023-08-26 02:33 UTC, Revincx commented
> 你可以 `git rebase -i origin/master` 整理一下

整理好了，留三个 commit 应该没什么问题吧

2023-08-26 03:04 UTC, Revincx commented
> 你準備好之後就可以合併了～

👀

2023-08-26 03:17 UTC, merged