fix: add some translation
qier222/YesPlayMusic pull request #2016
Opened 2023-03-27 14:22 UTC by Anmizi

添加设置区域的一些翻译

2023-04-05 11:19 UTC, pan93412 requested changes

2023-04-05 11:19 UTC, pan93412 commented on src/locale/lang/zh-TW.js
> +    customization: '自定義',
自訂

2023-04-05 11:19 UTC, pan93412 commented on src/views/settings.vue
> +      <!-- <h3>音质</h3> -->
Why commenting this?

2023-04-05 11:32 UTC, Anmizi commented on src/views/settings.vue
> +      <!-- <h3>音质</h3> -->
因为音质列表下只有music quality这一个选项，我觉得也许没必要再弄一个"音质"的大标题了
修改前：
![Snipaste_2023-04-05_19-31-10](https://user-images.githubusercontent.com/69138726/230068175-e440a004-3c41-46f0-864e-8573c67f7cb2.png)
修改后：
![Snipaste_2023-04-05_19-31-28](https://user-images.githubusercontent.com/69138726/230068265-056819e5-e43c-42a9-8512-76ef54e172a7.png)

2023-06-05 14:50 UTC, pan93412 commented on src/locale/lang/zh-TW.js
> +    customization: '自定義',
@Anmizi waiting for your fix!

2023-06-05 15:15 UTC, pan93412 commented on src/locale/lang/zh-TW.js
> +    customization: '自定義',
yeah, 台灣比較習慣「自訂」

2023-06-05 15:16 UTC, Anmizi commented on src/locale/lang/zh-TW.js
> +    customization: '自定義',
@pan93412 OK，了解

2023-06-05 15:50 UTC, Anmizi commented on src/locale/lang/zh-TW.js
> +    customization: '自定義',
@pan93412 已经修改了

2023-06-18 05:50 UTC, pan93412 approved these changes

2023-07-03 04:45 UTC, merged